name: Daily Auto Commit

run-name: 24f2004163@ds.study.iitm.ac.in Daily Scheduled Run

on:
  schedule:
    - cron: '13 4 * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scheduled Step
        run: |
          echo "Updated on $(date)" >> daily_log.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "24f2004163@ds.study.iitm.ac.in"
          git add daily_log.txt
          git commit -m "Automated daily commit on $(date)" || echo "No changes"
          git push
